pull_request_rules:

- name: Automatically approve bot PRs
  conditions: &base_merge_conditions
  - status-success=ShellCheck
  - status-success=GitHub workflows check
  - status-success=Scalafmt check
  - status-success=Run tests
  - status-success=Build Docker image
  - or:
    - author=horothesun-scala-steward[bot]
    - author=horothesun-renovate[bot]
  actions:
    review:
      type: APPROVE

- name: Automatically merge bot PRs
  conditions:
  - and: *base_merge_conditions
  - and:
    - "#approved-reviews-by>=1"
  actions:
    merge:
      method: squash
