pull_request_rules:
- name: Automatically merge Scala Steward PRs
  conditions:
  - author=horothesun-scala-steward[bot]
  - "#approved-reviews-by>=1"
  - status-success=ShellCheck
  - status-success=GitHub workflows check
  - status-success=Scalafmt check
  - status-success=Run tests
  - status-success=Build Docker image
  actions:
    merge:
      method: squash
